Army_Calculator/urls.py
"""
Definition of urls for Army_Calculator.
"""

from datetime import datetime
from django.urls import path, include
from django.contrib import admin
from django.contrib.auth.views import LoginView, LogoutView
from . import views


urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('contact/', views.ContactView.as_view(), name='contact'),
    path('about/', views.AboutView.as_view(), name='about'),
    path('loginsuccess/', views.LoginsuccessView.as_view(), name='loginsuccess'),
    path('contactsuccess/', views.ContactsuccessView.as_view(), name='contactsuccess'),
    path('thanks/', views.ThanksView.as_view(), name='thanks'),
    path('accounts/', include("accounts.urls", namespace="accounts")),
    path('accounts/', include("django.contrib.auth.urls")),
    path('movement/', include("movement.urls", namespace="movement")),
    path('startex/', include("startex.urls", namespace="startex")),
    # path('login/',
    #      LoginView.as_view
    #      (
    #          template_name='app/login.html',
    #          authentication_form=forms.BootstrapAuthenticationForm,
    #          extra_context=
    #          {
    #              'title': 'Log in',
    #              'year' : datetime.now().year,
    #          }
    #      ),
    #      name='login'),
    # path('logout/', LogoutView.as_view(next_page='/'), name='logout'),
    path('admin/', admin.site.urls),
]

startex/urls.py
from django.urls import path
from startex import views

app_name = 'startex'

urlpatterns = [
    # FBV
    path('post/ajax/startex_plan', views.post_StartEx_Plan, name="post_startex_plan"),
    path('post/ajax/sx_unit_detail', views.post_Unit_Detail, name="post_unit_detail"),
    path('get/ajax/sx_unit_detail', views.get_Unit_Detail, name="get_unit_detail"),
    path('get/ajax/sx_vehicle_detail', views.get_Vehicle_Detail, name="get_vehicle_detail"),
    path('get/ajax/validate_vehicle_name', views.validate_Vehicle_Name, name="validate_vehicle_name"),
    path('get/ajax/validate_sx_unit_name', views.validate_SX_Unit_Name, name="validate_sx_unit_name"),
    path('get/ajax/validate_sx_vehicle_name', views.validate_SX_Vehicle_Name, name="validate_sx_vehicle_name"),
    # Base
    path('', views.StartEx_PlanBaseView.as_view(), name="startex_plan_base"),
    # View
    path('list_startex_plan/', views.List_StartEx_PlanView.as_view(), name="list_startex_plan"),
    path("detail_startex_plan/<int:pk>/", views.Detail_StartEx_PlanView.as_view(), name="detail_startex_plan"),
    # Create
    path("create_list_sx_vehicle_data/", views.Create_List_SX_Vehicle_DataView.as_view(),
         name="create_list_sx_vehicle_data"),
    path("create_startex_plan/", views.Create_StartEx_PlanView.as_view(), name="create_startex_plan"),
    path("create_list_sx_unit_detail/", views.Create_List_SX_Unit_DetailView.as_view(),
         name="create_list_sx_unit_detail"),
    path("create_list_sx_vehicle_detail/", views.Create_List_SX_Vehicle_DetailView.as_view(),
         name="create_list_sx_vehicle_detail"),
    # Edit
    path("list_edit_vehicle_data/", views.list_edit_vehicle_dataView.as_view(), name="list_edit_vehicle_data"),
    path("list_edit_startex_plan/", views.List_Edit_StartEx_PlanView.as_view(), name="list_edit_startex_plan"),
    path("list_edit_sx_unit_detail/", views.List_Edit_SX_Unit_DetailView.as_view(), name="list_edit_sx_unit_detail"),
    path("list_edit_sx_vehicle_detail/", views.List_Edit_SX_Vehicle_DetailView.as_view(),
         name="list_edit_sx_vehicle_detail"),
    # Update
    path("update_sx_vehicle_data/<int:pk>/", views.Update_SX_Vehicle_DataView.as_view(), name="update_sx_vehicle_data"),
    path("update_startex_plan/<int:pk>/", views.Update_StartEx_PlanView.as_view(), name="update_startex_plan"),
    path("update_sx_unit_detail/<int:pk>/", views.Update_SX_Unit_DetailView.as_view(), name="update_sx_unit_detail"),
    path("update_sx_vehicle_detail/<int:pk>/", views.Update_SX_Vehicle_DetailView.as_view(),
         name="update_sx_vehicle_detail"),
    # Delete
    path("delete_sx_vehicle_data/<int:pk>/", views.Delete_SX_Vehicle_DataView.as_view(), name="delete_sx_vehicle_data"),
    path("delete_startex_plan/<int:pk>/", views.Delete_StartEx_PlanView.as_view(), name="delete_startex_plan"),
    path("delete_sx_unit_detail/<int:pk>/", views.Delete_SX_Unit_DetailView.as_view(), name="delete_sx_unit_detail"),
    path("delete_sx_vehicle_detail/<int:pk>/", views.Delete_SX_Vehicle_DetailView.as_view(), name="delete_sx_vehicle_detail"),
]

startex/models.py
from django.db import models
from django.urls import reverse
import movement.models as mm

from django.contrib.auth import get_user_model

User = get_user_model()


# Create your models here.
class StartEx_Plan(models.Model):
    name = models.CharField(max_length=250, null=False, blank=False)
    brigade = models.ForeignKey(mm.Brigade, related_name="startex_plan", on_delete=models.PROTECT)
    description = models.TextField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now=True)
    created_by = models.ForeignKey(User, related_name="startex_plan", on_delete=models.PROTECT)

    def __str__(self):
        return str(self.pk) + " - " + str(self.name)

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

    def get_detailview_url(self):
        return reverse(
            "startex:detail_startex_plan",
            kwargs={
                "pk": self.pk,
            }
        )

    def get_update_url(self):
        return reverse(
            "startex:update_startex_plan",
            kwargs={
                "pk": self.pk,
            }
        )

    def get_delete_url(self):
        return reverse(
            "startex:delete_startex_plan",
            kwargs={
                "pk": self.pk,
            }
        )

    class Meta:
        ordering = ["-created_at"]


class SX_Vehicle_Data(models.Model):
    VEHICLE_CATEGORY = (
        ('A', 'A'),
        ('B', 'B'),
        ('B+E', 'B+E'),
        ('C', 'C'),
        ('C+E', 'C+E'),
        ('D1', 'D1'),
        ('D', 'D'),
        ('D+E', 'D+E'),
    )
    name = models.CharField(max_length=150, null=False, blank=False)
    model = models.CharField(max_length=250, null=False, blank=False)
    category = models.CharField(max_length=250, null=False, blank=False, choices=VEHICLE_CATEGORY)

    def __str__(self):
        return self.name

    def get_update_url(self):
        return reverse(
            "startex:update_sx_vehicle_data",
            kwargs={
                "pk": self.pk,
            }
        )

    def get_delete_url(self):
        return reverse(
            "startex:delete_sx_vehicle_data",
            kwargs={
                "pk": self.pk,
            }
        )


class SX_Unit_Detail(models.Model):
    sx_id = models.ForeignKey(StartEx_Plan, related_name="sx_unit_detail", on_delete=models.CASCADE)
    u_id = models.ForeignKey(mm.Unit, related_name="sx_unit_detail", on_delete=models.PROTECT)

    def __str__(self):
        return str(self.sx_id) + " - " + str(self.u_id)

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

    def get_update_url(self):
        return reverse(
            "startex:update_sx_unit_detail",
            kwargs={
                "pk": self.pk,
            }
        )

    def get_delete_url(self):
        return reverse(
            "startex:delete_sx_unit_detail",
            kwargs={
                "pk": self.pk,
            }
        )

    class Meta:
        ordering = ["id"]


class SX_Vehicle_Detail(models.Model):
    sx_u_id = models.ForeignKey(SX_Unit_Detail, related_name="sx_vehicle_detail", on_delete=models.CASCADE)
    sx_v_id = models.ForeignKey(SX_Vehicle_Data, related_name="sx_vehicle_detail", on_delete=models.PROTECT)
    qty = models.PositiveIntegerField(null=False, blank=False)

    def __str__(self):
        return str(self.sx_u_id) + " - " + str(self.sx_v_id)

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

    def get_update_url(self):
        return reverse(
            "startex:update_sx_vehicle_detail",
            kwargs={
                "pk": self.pk,
            }
        )

    def get_delete_url(self):
        return reverse(
            "startex:delete_sx_vehicle_detail",
            kwargs={
                "pk": self.pk,
            }
        )

    class Meta:
        ordering = ["id"]

startex/forms.py
import datetime
from django import forms
from startex import models
from django.core.exceptions import ValidationError

class StartEx_PlanForm(forms.ModelForm):
    class Meta:
        model = models.StartEx_Plan
        exclude = ('created_by', 'created_at')

        widgets = {
            'description': forms.Textarea(attrs={'class': 'editable medium-editor-textarea'})
        }

    # def __init__(self, *args, **kwargs):
    #     super(StartEx_PlanForm, self).__init__(*args, **kwargs)
        # self.fields['created_at'].label = "Creation date"
        # self.fields['created_by'].label = "Created by"


class SX_Unit_DetailForm(forms.ModelForm):
    class Meta:
        model = models.SX_Unit_Detail
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super(SX_Unit_DetailForm, self).__init__(*args, **kwargs)
        self.fields['sx_id'].label = "Applies to StartEx"
        self.fields['u_id'].label = "Unit"


class SX_Vehicle_DetailForm(forms.ModelForm):
    class Meta:
        model = models.SX_Vehicle_Detail
        fields = '__all__'
        # exclude = ('packet_allocated', 'packet_auto_populted',)

    def __init__(self, *args, **kwargs):
        super(SX_Vehicle_DetailForm, self).__init__(*args, **kwargs)
        self.fields['sx_u_id'].label = "Applies to unit"
        self.fields['sx_v_id'].label = "Vehicle Name"
        self.fields['qty'].label = "Quantity"


class SX_Vehicle_DataForm(forms.ModelForm):
    class Meta:
        model = models.SX_Vehicle_Data
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super(SX_Vehicle_DataForm, self).__init__(*args, **kwargs)
        self.fields['name'].label = "Vehicle name"
        self.fields['model'].label = "Vehicle model"
        self.fields['category'].label = "Vehicle category"

startex/templates/startex/create_list_sx_unit_detail.html
{% extends "./startex_layout.html" %}

{% block breadcrumb %}
    <li class="breadcrumb-item active"><a href="{% url 'startex:startex_plan_base' %}">StartEx</a></li>
    <li class="breadcrumb-item active"><a href="{% url 'startex:create_startex_plan' %}">Create StartEX Plan</a></li>
    <li class="breadcrumb-item active">Create Unit Allocation</li>
{% endblock %}

{% block searchbar %}
    <form class="d-flex" action="{% url 'startex:create_list_sx_unit_detail' %}">
      {% csrf_token %}
      <input class="form-control me-2" type="search" placeholder="StartEx - Search" aria-label="Search" name="search">
      <button class="btn btn-success me-2" type="submit">Search</button>
    </form>
{% endblock %}

{% block content %}
    {% if request.user.is_authenticated %}
        <div id="liveAlertPlaceholder"></div>
        {% if searchbool %}
            <div class="container">
                <hr class="bg-danger border-2 border-top border-danger">
                <h2>Search Result</h2><br>
                {% if unit_details %}
                    {% for unit_detail in unit_details %}
                        <h3>{{forloop.counter}}. {{unit_detail.sx_id}}</h3>
                        <p class="lead">ID: {{unit_detail.id}}</p>
                        <p>Unit: {{unit_detail.u_id}}</p>
                    {% endfor %}
                {% else %}
                    <p>Not found </p>
                {% endif %}
                <hr class="bg-danger border-2 border-top border-danger">
            </div>
        {% endif %}

        <div class="container">
          <div class="alert alert-info lead" role="alert">
            Create Unit Allocation
          </div>
          {% load django_bootstrap5 %}
            <div class="container">
                <form method="POST" class="form">
                    {% csrf_token %}
                    {% bootstrap_form form layout='horizontal' %}
                    {% bootstrap_button button_type="submit" class="btn btn-primary" content="Add" %}
                    {% if sx_guide == 0 %}
                        <span class="spinner-grow spinner-grow-sm" role="status" aria-hidden="true"></span>
                    {% endif %}
                    <a id = 'id_done' class="ms-3 btn btn-primary" href="{% url done_url %}" role="button">{{ done_text }}</a>
              </form>
            </div>

            <div class="mt-5 alert alert-secondary lead" role="alert">
                List of allocated units
            </div>

            <div class="row justify-content-left">
                <div class="col-auto">
                    {% if create_list_sx_unit_detail %}
                      <table id = "id_list_sx_unit_detail" class="table table-responsive table-striped table-bordered border-secondary mb-4">
                        <thead class="table-dark">
                          <tr>
                            <th>StartEx ID</th>
                            <th>Unit</th>
                            <th>Action</th>
                          </tr>
                        </thead>
                        <tbody>
                            {% if create_list_sx_unit_detail %}
                                {% regroup create_list_sx_unit_detail by sx_id as sx_unit_detail_by_sx_id %}
                                    {% for sx_id in sx_unit_detail_by_sx_id %}
                                        <tr>
                                            <td>{{ sx_id.grouper }}</td>
                                            <td>
                                            {% for name in sx_id.list %}
                                                <div class="border-bottom" style="height:40px;">{{name.u_id}}</div>
                                            {% endfor %}
                                            </td>
                                            <td>
                                            {% for sx_unit_detail in create_list_sx_unit_detail %}
                                                <div class="border-bottom" style="height:40px;">
                                                    <a href="{{ sx_unit_detail.get_delete_url }}" class="btn btn-danger btn-sm bi bi-x-square"></a>
                                                    <a href="{{ sx_unit_detail.get_update_url }}" class="btn btn-primary btn-sm bi bi-pen"></a>
                                                    <form class="ajax_open_form btn">
                                                        {% csrf_token %}
                                                        <input type="submit" id="uid-{{sx_unit_detail.id}}" class="btn btn-primary btn-sm" value="Open" />
                                                        {% if forloop.counter == 1 %}
                                                            {% if sx_guide == 1 %}
                                                                <span class="spinner-grow spinner-grow-sm" role="status" aria-hidden="true"></span>
                                                            {% endif %}
                                                        {% endif %}
                                                    </form>
                                                </div>
                                            {% endfor %}
                                            </td>
                                        </tr>
                                    {% endfor %}
                            {% endif %}
                        </tbody>
                      </table>

                      {% include 'startex/pagination.html' %}

                    {% else %}
                        <p>There are no records!</p>
                    {% endif %}
                </div>
            </div>

            <script>
              $('#id_sx_id').val({{ sx_id }});
            </script>
            </div>
      {% else %}
		<h1> You are not logged in</h1>
	{% endif %}
{% endblock %}

{% block scripts %}
<script>
    $("#id_sx_id").change(function (e) {
        e.preventDefault();
        // get the nickname
        var sx_id = $(this).val();
        // GET AJAX request
        $.ajax({
            type: 'GET',
            url: "{% url 'startex:get_unit_detail' %}",
            data: {"sx_id": sx_id},
            success: function (response) {
                location.reload();
            },
            error: function (response) {
                console.log(response)
            }
        })
    })

    $("#id_u_id").change(function () {
      var sx_id = $('#id_sx_id').val();
      var sx_unit_name = $(this).val();
      $.ajax({
        type: 'GET',
        url: "{% url 'startex:validate_sx_unit_name' %}",
        data: {
          'sx_unit_name': sx_unit_name,
          'sx_id': sx_id
        },
        dataType: 'json',
        success: function (data) {
          if (data.is_taken) {
            alert(data.error_message);
            var vehName = $("#id_u_id");
            vehName.val("")
            vehName.focus()
          }
        }
      });
    });

    $(".ajax_open_form").submit(function (e) {
        var sx_plan_id = $(this).closest('tr').children('td:first').text().split(" - ")[0];
        var sx_unit_id = $(this).children('input:last').attr("id").split("-")[1];
        // preventing from page reload and default actions
        e.preventDefault();
        // serialize the data for sending the form data.
        var serializedData = $(this).serialize() + '&sx_plan_id=' + sx_plan_id + '&sx_unit_id=' + sx_unit_id;
        // Url
        var url = "{% url 'startex:create_list_sx_vehicle_detail' %}"
        // make POST ajax call
        $.ajax({
            type: 'POST',
            url: "{% url 'startex:post_unit_detail' %}",
            data: serializedData,
            success: function (response) {
                window.location = url
            },
            error: function (response) {
                // alert the error if any error occured
                alert(response["responseJSON"]["error"]);
            }
        })
    })

    // Alert - Start
    var alertPlaceholder = document.getElementById('liveAlertPlaceholder');
    function alert_guide(header, body, extra, instruction, furtherinfo) {
        let code = "";
        code += "<div class=\"alert alert-success\" role=\"alert\">\n";
        code += "<p class=\"text-center bg-secondary text-white\">(Guide Mode)</p>\n";
        code += "  <h4 class=\"alert-heading\">" + header + "</h4>\n";
        code += "  <p>" + body + "</p>\n";
        code += "  " + extra + "\n";
        code += "  " + instruction + "\n";
        code += "  <p></br>" + furtherinfo + "</p>\n";
        code += "  <hr>\n";
        code += "  <p class=\"mb-0 alert alert-warning\"><small><strong>Note:</strong> The administrator has activated \
                    the guide mode on this web application.\n";

        code += "</div>\n";

        var wrapper = document.createElement('div');
        wrapper.innerHTML = code;
        alertPlaceholder.append(wrapper);
    }

    $(document).ready(function () {
        var header = "Next, allocate units!";
        var body = "The units you allocate here will be earmarked for Ex Brighton Drive. To allocate, select a unit \
        from the dropdown box and then click the \"<code>Add</code>\" button. Repeat the process to allocate more units to the exercise.";
        var extra = "<h5>For example:</h5>";
        var instruction = "<b>Unit: </b> 1 MERC";
        var furtherinfo = "After you've added the unit, you can make changes by clicking the \"<code>Delete</code>\" or \"<code>Update</code>\" \
                    buttons. Finally, click the \"<code>Open</code>\" button, in turn, to allocate vehicle and quantity to the unit opened.";
        alert_guide(header, body, extra, instruction, furtherinfo);
    });
    // Alert - End
</script>
{% endblock scripts %}

startex/templates/startex/create_list_sx_vehicle_detail.html
{% extends "./startex_layout_view.html" %}

{% block breadcrumb %}
    <li class="breadcrumb-item active"><a href="{% url 'startex:startex_plan_base' %}">StartEx</a></li>
    <li class="breadcrumb-item active"><a href="{% url 'startex:create_startex_plan' %}">Create StartEX Plan</a></li>
    <li class="breadcrumb-item active"><a id = "id_breadcrumb_second" href="{% url 'startex:create_list_sx_unit_detail' %}">Create Unit Allocation</a></li>
    <li class="breadcrumb-item active">Create Vehicle Allocation</li>
{% endblock %}

{% block searchbar %}
    <form class="d-flex" action="{% url 'startex:create_list_sx_vehicle_detail' %}">
      {% csrf_token %}
      <input class="form-control me-2" type="search" placeholder="StartEx - Search" aria-label="Search" name="search">
      <button class="btn btn-success me-2" type="submit">Search</button>
    </form>
{% endblock %}

{% block content %}
    {% if request.user.is_authenticated %}
        <div id="liveAlertPlaceholder"></div>
        {% if searchbool %}
            <div class="container">
                <hr class="bg-danger border-2 border-top border-danger">
                <h2>Search Result</h2><br>
                {% if vehicle_details %}
                    {% for vehicle_detail in vehicle_details %}
                        <h3>{{forloop.counter}}. {{vehicle_detail.sx_u_id}}</h3>
                        <p class="lead">ID: {{vehicle_detail.id}}</p>
                        <p>Vehicle: {{vehicle_detail.sx_v_id}}</p>
                        <p>Qty: {{vehicle_detail.qty}}</p>
                    {% endfor %}
                {% else %}
                    <p>Not found </p>
                {% endif %}
                <hr class="bg-danger border-2 border-top border-danger">
            </div>
        {% endif %}

        <div class="container">
            <div class="alert alert-info lead" role="alert">
                Add Unit
            </div>
        {% load django_bootstrap5 %}
        <div class="container">
            <form method="POST" class="form">
                {% csrf_token %}
                {% bootstrap_form form layout='horizontal' %}
                {% bootstrap_button button_type="submit" class="btn btn-primary" content="Add" %}
                {% if sx_guide == 0 %}
                    <span class="spinner-grow spinner-grow-sm" role="status" aria-hidden="true"></span>
                {% endif %}
                <a id = 'id_done' class="ms-3 btn btn-primary" href="{% url done_url %}" role="button">{{ done_text }}</a>
            </form>
        </div>

        <div class="mt-5 alert alert-secondary lead" role="alert">
            List of allocated vehicles
        </div>


        <div class="row justify-content-left">
                <div class="col-auto">
                {% if create_list_sx_vehicle_detail %}
                  <table id="id_list_sx_vehicle_detail" class="table table-responsive table-striped table-bordered border-secondary mb-4">
                      <thead class="table-dark">
                        <tr>
                            <th>StartEx ID</th>
                            <th>Vehicle</th>
                            <th>Qty</th>
                            <th>Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% if create_list_sx_vehicle_detail %}
                        {% regroup create_list_sx_vehicle_detail by sx_u_id as sx_vehicle_detail_by_sx_u_id %}
                            {% for sx_u_id in sx_vehicle_detail_by_sx_u_id %}
                                <tr>
                                    <td>{{ sx_u_id.grouper }}</td>
                                    <td>
                                    {% for list in sx_u_id.list %}
                                        <div class="border-bottom" style="height:40px;">{{list.sx_v_id}}</div>
                                    {% endfor %}
                                    </td>
                                    <td>
                                    {% for list in sx_u_id.list %}
                                        <div class="border-bottom" style="height:40px;">{{list.qty}}</div>
                                    {% endfor %}
                                    </td>
                                    <td>
                                    {% for vehicle_detail in create_list_sx_vehicle_detail %}
                                        <div class="border-bottom" style="height:40px;">
                                            <a href="{{ vehicle_detail.get_delete_url }}" class="btn btn-danger btn-sm bi bi-x-square"></a>
                                            <a href="{{ vehicle_detail.get_update_url }}?reverse=true" class="btn btn-primary btn-sm bi bi-pen"></a>
                                        </div>
                                    {% endfor %}
                                    </td>
                                </tr>
                            {% endfor %}
                    {% endif %}
                    </tbody>
                  </table>

                  {% include 'startex/pagination.html' %}

                {% else %}
                    <p>There are no records!</p>
                {% endif %}
                </div>
            </div>

        <script>
            $('#id_sx_u_id').val({{ sx_u_id }});
        </script>
            </div>
      {% else %}
		<h1> You are not logged in</h1>
	{% endif %}
{% endblock %}

{% block scripts %}
<script>
    // Alert - Start
    var alertPlaceholder = document.getElementById('liveAlertPlaceholder');
    function alert_guide(header, body, extra, instruction, furtherinfo) {
        let code = "";
        code += "<div class=\"alert alert-success\" role=\"alert\">\n";
        code += "<p class=\"text-center bg-secondary text-white\">(Guide Mode)</p>\n";
        code += "  <h4 class=\"alert-heading\">" + header + "</h4>\n";
        code += "  <p>" + body + "</p>\n";
        code += "  " + extra + "\n";
        code += "  " + instruction + "\n";
        code += "  <p></br>" + furtherinfo + "</p>\n";
        code += "  <hr>\n";
        code += "  <p class=\"mb-0 alert alert-warning\"><small><strong>Note:</strong> The administrator has activated \
                    the guide mode on this web application.\n";

        code += "</div>\n";

        var wrapper = document.createElement('div');
        wrapper.innerHTML = code;
        alertPlaceholder.append(wrapper);
    }

    $(document).ready(function () {
        var header = "Finally, allocate vehicles!";
        var body = "Select a vehicle name from the dropdown box, enter the vehicle quantity, and then click the \"<code>Add</code>\" \
                button to allocate the vehicle to the unit you've opened. Repeat the process to allocate more vehicles to \
                the unit you've opened.";
        var extra = "<h5>For example:</h5>";
        var instruction = "<b>Vehicle Name: </b> MLRS</br><b>Quantity: </b>20";
        var furtherinfo = "After you've allocated vehicles, you can make changes to them by clicking the \"<code>Delete</code>\" or \"<code>Update</code>\" \
                    buttons. In the meantime, click on the \"<code>Back</code>\" button to allocate vehicles to other units. Alternatively, you can use the dropdown. Finally, please select \"<code>StartEx Plan</code>\" from the \"<code>View</code>\" dropdown menu on the left vertical \
                    navbar to view the StartEx plan you have just created.";
        alert_guide(header, body, extra, instruction, furtherinfo);
    });
    // Alert - End

    $("#id_sx_u_id").change(function (e) {
        e.preventDefault();
        // get the nickname
        var sx_unit_id = $(this).val();
        // GET AJAX request
        $.ajax({
            type: 'GET',
            url: "{% url 'startex:get_vehicle_detail' %}",
            data: {"sx_unit_id": sx_unit_id},
            success: function (response) {
                location.reload();
            },
            error: function (response) {
                console.log(response)
            }
        })
    })

    $("#id_sx_v_id").change(function () {
      var sx_u_id = $('#id_sx_u_id').val();
      var sx_vehicle_name = $(this).val();
      $.ajax({
        type: 'GET',
        url: "{% url 'startex:validate_sx_vehicle_name' %}",
        data: {
          'sx_vehicle_name': sx_vehicle_name,
          'sx_u_id': sx_u_id
        },
        dataType: 'json',
        success: function (data) {
          if (data.is_taken) {
            alert(data.error_message);
            var vehName = $("#id_sx_v_id");
            vehName.val("")
            vehName.focus()
          }
        }
      });
    });


</script>
{% endblock scripts %}

startex/templates/startex/delete_sx_unit_detail.html
{% extends "./startex_layout.html" %}

{% block breadcrumb %}
  	<li class="breadcrumb-item active"><a href="{% url 'startex:startex_plan_base' %}">StartEx</a></li>
	<li class="breadcrumb-item active">Confirm Delete Unit Detail</li>
{% endblock %}

{% block content %}
	{% if request.user.is_authenticated %}
		<div class="container">
		  	<div class="alert alert-danger lead" role="alert">Confirm Delete Unit Detail</div>
			  {% load django_bootstrap5 %}
				<div class="container">
					<form method="POST" class="form">
						{% csrf_token %}
					  	<p>Are you sure you want to delete Unit Detail "{{ object.u_id }}"?</p>
						{% bootstrap_button button_type="submit" class="btn btn-primary" content="Confirm" %}
						<a class="ms-3 btn btn-primary" href="{% url cancel_url %}" role="button">Cancel</a>
				  	</form>
				</div>
  	{% else %}
		<h1> You are not logged in</h1>
  	{% endif %}
		</div>
{% endblock %}