Army_Calculator/urls.py
"""
Definition of urls for Army_Calculator.
"""

from datetime import datetime
from django.urls import path, include
from django.contrib import admin
from django.contrib.auth.views import LoginView, LogoutView
from . import views


urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('contact/', views.ContactView.as_view(), name='contact'),
    path('about/', views.AboutView.as_view(), name='about'),
    path('loginsuccess/', views.LoginsuccessView.as_view(), name='loginsuccess'),
    path('contactsuccess/', views.ContactsuccessView.as_view(), name='contactsuccess'),
    path('thanks/', views.ThanksView.as_view(), name='thanks'),
    path('accounts/', include("accounts.urls", namespace="accounts")),
    path('accounts/', include("django.contrib.auth.urls")),
    path('movement/', include("movement.urls", namespace="movement")),
    path('startex/', include("startex.urls", namespace="startex")),
    # path('login/',
    #      LoginView.as_view
    #      (
    #          template_name='app/login.html',
    #          authentication_form=forms.BootstrapAuthenticationForm,
    #          extra_context=
    #          {
    #              'title': 'Log in',
    #              'year' : datetime.now().year,
    #          }
    #      ),
    #      name='login'),
    # path('logout/', LogoutView.as_view(next_page='/'), name='logout'),
    path('admin/', admin.site.urls),
]

accounts/urls.py
from datetime import datetime
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'accounts'

urlpatterns = [
    path('login/',
        auth_views.LoginView.as_view
        (
            template_name="accounts/login.html",
            extra_context=
                      {
                          'title': 'Log in',
                          'sidebar': 'Account',
                          'year' : datetime.now().year,
                      }
        ),
        name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name="logout"),
    path('signup/', views.SignUp.as_view(), name="signup"),
    path('contact/', views.ContactView.as_view(), name="contact"),
]

movement/urls.py
from django.urls import path
from . import views

app_name = 'movement'

urlpatterns = [
    # FBV
    path('post/ajax/movement_plan', views.post_Movement_Plan, name="post_movement_plan"),
    path('post/ajax/m_cp_detail', views.post_CP_Detail, name="post_cp_detail"),
    path('get/ajax/m_cp_detail', views.get_CP_Detail, name="get_cp_detail"),
    path('post/ajax/m_unit_detail', views.post_Unit_Detail, name="post_unit_detail"),
    path('get/ajax/m_unit_detail', views.get_Unit_Detail, name="get_unit_detail"),
    path('get/ajax/m_packet_detail', views.get_Packet_Detail, name="get_packet_detail"),
    path('get/ajax/validate_brigade_name', views.validate_Brigade_Name, name="validate_brigade_name"),
    path('get/ajax/validate_brigade_acronym_name', views.validate_Brigade_Acronym_Name, name="validate_brigade_acronym_name"),
    path('get/ajax/validate_unit_name', views.validate_Unit_Name, name="validate_unit_name"),
    path('get/ajax/validate_unit_acronym_name', views.validate_Unit_Acronym_Name, name="validate_unit_acronym_name"),
    path('get/ajax/validate_mov_cp_no', views.validate_Mov_CP_No, name="validate_mov_cp_no"),
    path('get/ajax/validate_mov_unit_name', views.validate_Mov_Unit_Name, name="validate_mov_unit_name"),
    path('get/ajax/validate_mov_subunit_name', views.validate_Mov_SubUnit_Name, name="validate_mov_subunit_name"),
    path('get/ajax/validate_mov_subunit_pkt_no', views.validate_Mov_SubUnit_Pkt_No, name="validate_mov_subunit_pkt_no"),
    path('get/ajax/get_sx_plan', views.get_SX_Plan, name="get_sx_plan"),
    path('get/ajax/get_btn_text', views.get_Btn_Text, name="get_btn_text"),
    path('get/ajax/validate_mov_veh_qty', views.validate_Mov_Veh_Qty, name="validate_mov_veh_qty"),
    # Base
    path('', views.Movement_PlanBaseView.as_view(), name="movement_plan_base"),
    # View
    path('list_movement_plan/', views.Movement_PlanListView.as_view(), name="list_movement_plan"),
    path("<brigade>/<int:pk>/", views.Movement_PlanDetailView.as_view(), name="detail_movement_plan"),
    path("<brigade>/<unit>/<int:pk>/", views.Unit_DetailView.as_view(), name="detail_movement_plan_by_unit"),
    # Create
    path("create_list_unit/", views.Create_UnitCreateListView.as_view(), name="create_list_unit"),
    path("create_list_brigade/", views.Create_BrigadeCreateListView.as_view(), name="create_list_brigade"),
    path("create_movement_plan/", views.Create_Movement_PlanView.as_view(), name="create_movement_plan"),
    path("create_list_mov_cp_detail/", views.Create_CP_DetailCreateListView.as_view(), name="create_list_mov_cp_detail"),
    path("create_list_mov_unit_detail/", views.Create_Unit_DetailCreateListView.as_view(), name="create_list_mov_unit_detail"),
    path("create_list_mov_packet_detail/", views.Create_Packet_DetailCreateListView.as_view(), name="create_list_mov_packet_detail"),
    # Edit
    path("list_edit_unit/", views.Edit_Unit_ListView.as_view(), name="list_edit_unit"),
    path("list_edit_brigade/", views.Edit_Brigade_ListView.as_view(), name="list_edit_brigade"),
    path("list_edit_movement_plan/", views.Edit_Movement_PlanListView.as_view(),
         name="list_edit_movement_plan"),
    path("list_edit_mov_cp_detail/", views.Edit_CP_DetailListView.as_view(), name="list_edit_mov_cp_detail"),
    path("list_edit_mov_unit_detail/", views.Edit_Unit_DetailListView.as_view(),
         name="list_edit_mov_unit_detail"),
    path("list_edit_mov_packet_detail/", views.Edit_Packet_DetailListView.as_view(),
         name="list_edit_mov_packet_detail"),
    # Update
    path("update_unit_<int:pk>/", views.Update_UnitView.as_view(), name="update_unit"),
    path("update_brigade_<int:pk>/", views.Update_BrigadeView.as_view(), name="update_brigade"),
    path("update_movement_plan_<int:pk>/", views.Update_Movement_PlanView.as_view(), name="update_movement_plan"),
    path("update_mov_cp_detail_<int:pk>/", views.Update_Mov_CP_DetailView.as_view(), name="update_mov_cp_detail"),
    path("update_mov_unit_detail_<int:pk>/", views.Update_Mov_Unit_DetailView.as_view(), name="update_mov_unit_detail"),
    path("update_mov_packet_detail_<int:pk>/", views.Update_Mov_Packet_DetailView.as_view(), name="update_mov_packet_detail"),
    # Delete
    path("delete_unit_<int:pk>/", views.Delete_UnitView.as_view(), name="delete_unit"),
    path("delete_brigade_<int:pk>/", views.Delete_BrigadeView.as_view(), name="delete_brigade"),
    path("delete_movement_plan_<int:pk>/", views.Delete_Movement_PlanView.as_view(), name="delete_movement_plan"),
    path("delete_mov_cp_detail_<int:pk>/", views.Delete_Mov_CP_DetailView.as_view(), name="delete_mov_cp_detail"),
    path("delete_mov_unit_detail_<int:pk>/", views.Delete_Mov_Unit_DetailView.as_view(), name="delete_mov_unit_detail"),
    path("delete_mov_packet_detail_<int:pk>/", views.Delete_Mov_Packet_DetailView.as_view(), name="delete_mov_packet_detail"),
]

startex/urls.py
from django.urls import path
from startex import views

app_name = 'startex'

urlpatterns = [
    # FBV
    path('post/ajax/startex_plan', views.post_StartEx_Plan, name="post_startex_plan"),
    path('post/ajax/sx_unit_detail', views.post_Unit_Detail, name="post_unit_detail"),
    path('get/ajax/sx_unit_detail', views.get_Unit_Detail, name="get_unit_detail"),
    path('get/ajax/sx_vehicle_detail', views.get_Vehicle_Detail, name="get_vehicle_detail"),
    path('get/ajax/validate_vehicle_name', views.validate_Vehicle_Name, name="validate_vehicle_name"),
    path('get/ajax/validate_sx_unit_name', views.validate_SX_Unit_Name, name="validate_sx_unit_name"),
    path('get/ajax/validate_sx_vehicle_name', views.validate_SX_Vehicle_Name, name="validate_sx_vehicle_name"),
    # Base
    path('', views.StartEx_PlanBaseView.as_view(), name="startex_plan_base"),
    # View
    path('list_startex_plan/', views.List_StartEx_PlanView.as_view(), name="list_startex_plan"),
    path("detail_startex_plan/<int:pk>/", views.Detail_StartEx_PlanView.as_view(), name="detail_startex_plan"),
    # Create
    path("create_list_sx_vehicle_data/", views.Create_List_SX_Vehicle_DataView.as_view(),
         name="create_list_sx_vehicle_data"),
    path("create_startex_plan/", views.Create_StartEx_PlanView.as_view(), name="create_startex_plan"),
    path("create_list_sx_unit_detail/", views.Create_List_SX_Unit_DetailView.as_view(),
         name="create_list_sx_unit_detail"),
    path("create_list_sx_vehicle_detail/", views.Create_List_SX_Vehicle_DetailView.as_view(),
         name="create_list_sx_vehicle_detail"),
    # Edit
    path("list_edit_vehicle_data/", views.list_edit_vehicle_dataView.as_view(), name="list_edit_vehicle_data"),
    path("list_edit_startex_plan/", views.List_Edit_StartEx_PlanView.as_view(), name="list_edit_startex_plan"),
    path("list_edit_sx_unit_detail/", views.List_Edit_SX_Unit_DetailView.as_view(), name="list_edit_sx_unit_detail"),
    path("list_edit_sx_vehicle_detail/", views.List_Edit_SX_Vehicle_DetailView.as_view(),
         name="list_edit_sx_vehicle_detail"),
    # Update
    path("update_sx_vehicle_data/<int:pk>/", views.Update_SX_Vehicle_DataView.as_view(), name="update_sx_vehicle_data"),
    path("update_startex_plan/<int:pk>/", views.Update_StartEx_PlanView.as_view(), name="update_startex_plan"),
    path("update_sx_unit_detail/<int:pk>/", views.Update_SX_Unit_DetailView.as_view(), name="update_sx_unit_detail"),
    path("update_sx_vehicle_detail/<int:pk>/", views.Update_SX_Vehicle_DetailView.as_view(),
         name="update_sx_vehicle_detail"),
    # Delete
    path("delete_sx_vehicle_data/<int:pk>/", views.Delete_SX_Vehicle_DataView.as_view(), name="delete_sx_vehicle_data"),
    path("delete_startex_plan/<int:pk>/", views.Delete_StartEx_PlanView.as_view(), name="delete_startex_plan"),
    path("delete_sx_unit_detail/<int:pk>/", views.Delete_SX_Unit_DetailView.as_view(), name="delete_sx_unit_detail"),
    path("delete_sx_vehicle_detail/<int:pk>/", views.Delete_SX_Vehicle_DetailView.as_view(), name="delete_sx_vehicle_detail"),
]

templates/contactsuccess.html
{% extends "layout_base.html" %}
{% block content %}
  <div class="alert alert-success" role="alert">
    Message saved successfully!
  </div>

  <script>
    $(document).ready(function(){
        $('#v-sidebar').removeClass('d-md-block');
        $('#h-sidebar').addClass('d-none');      
    });
  </script>
{% endblock %}

templates/layout.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ title }} - Army Calculator</title>
    {% load static %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.2/font/bootstrap-icons.css">
    <link rel="stylesheet" type="text/css" href="{% static 'army_calculator/content/css/master.css' %}" />
    <link href="https://cdn.jsdelivr.net/npm/remixicon@2.2.0/fonts/remixicon.css" rel="stylesheet">

        <!-- Latest compiled and minified jQuery -->
        <script src="https://code.jquery.com/jquery-3.6.0.js" integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk=" crossorigin="anonymous"></script>

        <!-- Activate navigation item of horizontal navbar based on the current page. -->
        <script>
          $(document).ready(function(){
            var title = $(document).attr('title');
            var title_split = title.split(' ');
            $('.h-nav').removeClass('active');
            $(('#h-nav-'+title_split[0]).toLowerCase()).addClass('active');
            if (title_split[0] == 'Home' || title_split[0] == 'About' || title_split[0] == 'Contact'){
              $('#v-sidebar').removeClass('d-md-block');
              $('#h-sidebar').addClass('d-none');
            }
            else{
              $('#v-sidebar').addClass('d-md-block');
              $('#h-sidebar').removeClass('d-none');
            }

            // Prevent the screen flicker.
            $("#main_tbody").css("display", "none");
            $("#main_tbody").fadeIn(500);
          });
        </script>
    </head>
    <body>

      <!-- Primary Navbar -->
        <div class="navbar navbar-expand-lg navbar-dark bg-secondary fixed-top">
            <div class="container-fluid">
                <!-- Navbar brand starts -->
                <a href="/" class="navbar-brand bi bi-calculator" href="{% url 'home' %}">Army Calculator</a>
                <!-- Ends -->

                <!--Navbar toggler icon starts -->
                <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <!-- Ends -->

                <!-- Collapsable navbar items starts        -->
                <div class="navbar-collapse collapse" id="navbarSupportedContent">

                    <!-- Navbar items start -->
                    {% if user.is_authenticated %}
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        <li class="nav-item"><a class="h-nav nav-link" href="{% url 'home' %}" id="h-nav-home">Home</a></li>
                        <li class="nav-item"><a class="h-nav nav-link" href="{% url 'startex:startex_plan_base' %}" id="h-nav-vehicle">StartEx</a></li>
                        <li class="nav-item"><a class="h-nav nav-link" href="{% url 'movement:movement_plan_base' %}" id="h-nav-movement">Movement</a></li>
                        <!-- <li class="nav-item"><a class="h-nav nav-link" href="" id="h-nav-report">Report</a></li> -->
                        <li class="nav-item"><a class="h-nav nav-link" href="{% url 'about' %}" id="h-nav-about">About</a></li>
                        <li class="nav-item"><a class="h-nav nav-link" href="{% url 'accounts:contact' %}" id="h-nav-contact">Contact</a></li>
                    </ul>
                    {% else %}
                      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                          <li class="nav-item"><a class="h-nav nav-link" href="{% url 'home' %}" id="h-nav-home">Home</a></li>
                          <li class="nav-item"><a class="h-nav nav-link" href="{% url 'about' %}" id="h-nav-about">About</a></li>
                          <li class="nav-item"><a class="h-nav nav-link" href="{% url 'accounts:contact' %}" id="h-nav-contact">Contact</a></li>
                      </ul>
                    {% endif %}
                    <!-- End -->

                    <!-- Search bar section starts -->
<!--                    method="POST"-->
                    {% block searchbar %}

                    {% endblock %}
                    <!-- Ends -->

                    <!-- Login section starts -->
                    {% if user.is_authenticated %}
                    <form class="d-flex" id="logoutForm" action="/accounts/logout/" method="POST">
                        {% csrf_token %}
                        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                            <li class="nav-item dropdown">
                              <a class="nav-link dropdown-toggle bi bi-person-circle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown"><span class="ms-2">Welcome {{ user.username }}!</span></a>
                              <ul class="dropdown-menu">
                                <li><a class="dropdown-item" href="javascript:document.getElementById('logoutForm').submit()">Log off</a></li>
                              </ul>
                            </li>
                        </ul>
                    </form>
                    {% else %}
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        <li class="h-nav nav-item"><a class="nav-link" href="{% url 'accounts:login' %}" id="h-nav-log">Log in</a></li>
                        <li class="h-nav nav-item"><a class="nav-link" href="{% url 'accounts:signup' %}" id="h-nav-sign">Sign up</a></li>
                    </ul>
                    {% endif %}
                    <!-- Ends -->

                </div>
                <!-- Ends -->

            </div>
        </div>
        <!-- Primary Navbar - Ends -->

        <!-- Secondary Navbar - This bar displays when display < medium -->
        <div class="d-md-none nav-scroller shadow-sm text-white bg-dark fixed-bottom" id='h-sidebar'>
          <nav class="nav nav-underline" aria-label="Secondary navigation">
              {% block secondary_navbar %}

              {% endblock secondary_navbar %}
          </nav>
        </div>
        <!-- Secondary Navbar - Ends -->

        <!-- Body -->

        <div class="d-flex flex-row mb-3">

          <div class="d-flex flex-column d-none d-md-block flex-shrink-0 p-3 text-white bg-dark" id = "v-sidebar" style="width: 230px;">
            <p class="d-flex align-items-center mb-3 mb-md-0 me-md-auto text-white text-decoration-none">
              <svg class="bi me-2" width="40" height="32"><use xlink:href="#bootstrap"/></svg>
              <span class="fs-4">{{ sidebar }}</span>
            </p>
            <hr>
            {% block primary_navbar %}

            {% endblock %}
          </div>

          <div class="b-vert-divider"></div>
          <div class="col d-flex flex-column bd-highlight">

            <div class="b-hori-divider"></div>
            <!-- Breadcrumb starts-->
            <div class="shadow-sm p-3 mb-3 bg-light rounded position-relative">
              <nav style="--bs-breadcrumb-divider: url(&#34;data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='8' height='8'%3E%3Cpath d='M2.5 0L1 1.5 3.5 4 1 6.5 2.5 8l4-4-4-4z' fill='currentColor'/%3E%3C/svg%3E&#34;);" aria-label="breadcrumb">
                <ol class="breadcrumb">
                  {% block breadcrumb %}

                  {% endblock %}
                </ol>
              </nav>
            </div>
            <!-- Ends -->
            <div class="p-2 bd-highlight">
              <div class="d-flex-container">
                {% block content %}

                {% endblock %}
              </div>
            </div>
          </div>

          <div class="b-vert-divider"></div>

        </div>

        <div class="container-fluid">
            <hr/>
            <footer>
                <p>&copy; {{ year }} - Army Calculator</p>
            </footer>
        </div>

        <!-- Master script for the site -->
        <script src="{% static 'army_calculator/scripts/master.js'%}" type="text/javascript" ></script>
        <!-- Latest compiled and minified JavaScript -->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

        <script src="{% static 'army_calculator/scripts/master.js' %}"></script>

      {% block scripts %}{% endblock %}
    </body>
    <script>
        // Popover - Start
            var popoverTriggerList = [].slice.call(document.querySelectorAll('[data-bs-toggle="popover"]'))
            var popoverList = popoverTriggerList.map(function (popoverTriggerEl) {
              return new bootstrap.Popover(popoverTriggerEl)
            })

            $(document).ready(function(){
                $('[data-toggle="popover"]').popover("show");
            });
            // Popover - End
    </script>
</html>

templates/layout_base.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ title }} - Army Calculator</title>
    {% load static %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.2/font/bootstrap-icons.css">
    <link rel="stylesheet" type="text/css" href="{% static 'army_calculator/content/css/master.css' %}" />

        <!-- Latest compiled and minified jQuery -->
        <script src="https://code.jquery.com/jquery-3.6.0.js" integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk=" crossorigin="anonymous"></script>

        <!-- Activate navigation item of horizontal navbar based on the current page. -->
        <script>
          $(document).ready(function(){
            var title = $(document).attr('title');
            var title_split = title.split(' ');
            $('.h-nav').removeClass('active');
            $(('#h-nav-'+title_split[0]).toLowerCase()).addClass('active');
            if (title_split[0] == 'Home' || title_split[0] == 'About' || title_split[0] == 'Contact'){
              $('#v-sidebar').removeClass('d-md-block');
              $('#h-sidebar').addClass('d-none');
            }
            else{
              $('#v-sidebar').addClass('d-md-block');
              $('#h-sidebar').removeClass('d-none');
            }

            // Prevent the screen flicker.
            $("#main_tbody").css("display", "none");
            $("#main_tbody").fadeIn(500);
          });

        </script>
    </head>
    <body>

      <!-- Primary Navbar -->
        <div class="navbar navbar-expand-lg navbar-dark bg-secondary fixed-top">
            <div class="container-fluid">
                <!-- Navbar brand starts -->
                <a href="/" class="navbar-brand bi bi-calculator" href="{% url 'home' %}">Army Calculator</a>
                <!-- Ends -->

                <!--Navbar toggler icon starts -->
                <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <!-- Ends -->

                <!-- Collapsable navbar items starts        -->
                <div class="navbar-collapse collapse" id="navbarSupportedContent">

                    <!-- Navbar items start -->
                    {% if user.is_authenticated %}
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        <li class="nav-item"><a class="h-nav nav-link" href="{% url 'home' %}" id="h-nav-home">Home</a></li>
                        <li class="nav-item"><a class="h-nav nav-link" href="{% url 'startex:startex_plan_base' %}" id="h-nav-vehicle">StartEx</a></li>
                        <li class="nav-item"><a class="h-nav nav-link" href="{% url 'movement:movement_plan_base' %}" id="h-nav-movement">Movement</a></li>
                        <!-- <li class="nav-item"><a class="h-nav nav-link" href="" id="h-nav-report">Report</a></li> -->
                        <li class="nav-item"><a class="h-nav nav-link" href="{% url 'about' %}" id="h-nav-about">About</a></li>
                        <li class="nav-item"><a class="h-nav nav-link" href="{% url 'accounts:contact' %}" id="h-nav-contact">Contact</a></li>
                    </ul>
                    {% else %}
                      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                          <li class="nav-item"><a class="h-nav nav-link" href="{% url 'home' %}" id="h-nav-home">Home</a></li>
                          <li class="nav-item"><a class="h-nav nav-link" href="{% url 'about' %}" id="h-nav-about">About</a></li>
                          <li class="nav-item"><a class="h-nav nav-link" href="{% url 'accounts:contact' %}" id="h-nav-contact">Contact</a></li>
                      </ul>
                    {% endif %}
                    <!-- End -->

                    <!-- Search bar section starts -->
<!--                    method="POST"-->
                    {% block searchbar %}

                    {% endblock %}
                    <!-- Ends -->

                    <!-- Login section starts -->
                    {% if user.is_authenticated %}
                    <form class="d-flex" id="logoutForm" action="/accounts/logout/" method="POST">
                        {% csrf_token %}
                        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                            <li class="nav-item dropdown">
                              <a class="nav-link dropdown-toggle bi bi-person-circle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown"><span class="ms-2">Welcome {{ user.username }}!</span></a>
                              <ul class="dropdown-menu">
                                <li><a class="dropdown-item" href="javascript:document.getElementById('logoutForm').submit()">Log off</a></li>
                              </ul>
                            </li>
                        </ul>
                    </form>
                    {% else %}
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        <li class="h-nav nav-item"><a class="nav-link" href="{% url 'accounts:login' %}" id="h-nav-log">Log in</a></li>
                        <li class="h-nav nav-item"><a class="nav-link" href="{% url 'accounts:signup' %}" id="h-nav-sign">Sign up</a></li>
                    </ul>
                    {% endif %}
                    <!-- Ends -->

                </div>
                <!-- Ends -->

            </div>
        </div>
        <!-- Primary Navbar - Ends -->

        <!-- Secondary Navbar - This bar displays when display < medium -->
        <div class="d-md-none nav-scroller shadow-sm text-white bg-dark fixed-bottom" id='h-sidebar'>
          <nav class="nav nav-underline" aria-label="Secondary navigation">
              {% block secondary_navbar %}

              {% endblock secondary_navbar %}
          </nav>
        </div>
        <!-- Secondary Navbar - Ends -->

        <!-- Body -->

        <div class="d-flex flex-row mb-3">

          <div class="d-flex flex-column d-none d-md-block flex-shrink-0 p-3 text-white bg-dark" id = "v-sidebar" style="width: 230px;">
            <p class="d-flex align-items-center mb-3 mb-md-0 me-md-auto text-white text-decoration-none">
              <svg class="bi me-2" width="40" height="32"><use xlink:href="#bootstrap"/></svg>
              <span class="fs-4">{{ sidebar }}</span>
            </p>
            <hr>
            {% block primary_navbar %}

            {% endblock %}
          </div>

          <div class="b-vert-divider"></div>
          <div class="col d-flex flex-column bd-highlight">

            <div class="b-hori-divider"></div>

            <div class="p-2 bd-highlight">
              <div class="d-flex-container">
                {% block content %}

                {% endblock %}
              </div>
            </div>
          </div>

          <div class="b-vert-divider"></div>

        </div>

        <div class="container-fluid">
            <hr/>
            <footer>
                <p>&copy; {{ year }} - Army Calculator</p>
            </footer>
        </div>

        <!-- Master script for the site -->
        <script src="{% static "army_calculator/scripts/master.js"%}" type="text/javascript" ></script>
        <!-- Latest compiled and minified JavaScript -->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    {% block scripts %}{% endblock %}

    </body>
    <script>
        // Popover - Start
            var popoverTriggerList = [].slice.call(document.querySelectorAll('[data-bs-toggle="popover"]'))
            var popoverList = popoverTriggerList.map(function (popoverTriggerEl) {
              return new bootstrap.Popover(popoverTriggerEl)
            })

            $(document).ready(function(){
                $('[data-toggle="popover"]').popover("show");
            });
            // Popover - End
    </script>
</html>