Army_Calculator/urls.py
"""
Definition of urls for Army_Calculator.
"""

from datetime import datetime
from django.urls import path, include
from django.contrib import admin
from django.contrib.auth.views import LoginView, LogoutView
from . import views


urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('contact/', views.ContactView.as_view(), name='contact'),
    path('about/', views.AboutView.as_view(), name='about'),
    path('loginsuccess/', views.LoginsuccessView.as_view(), name='loginsuccess'),
    path('contactsuccess/', views.ContactsuccessView.as_view(), name='contactsuccess'),
    path('thanks/', views.ThanksView.as_view(), name='thanks'),
    path('accounts/', include("accounts.urls", namespace="accounts")),
    path('accounts/', include("django.contrib.auth.urls")),
    path('movement/', include("movement.urls", namespace="movement")),
    path('startex/', include("startex.urls", namespace="startex")),
    # path('login/',
    #      LoginView.as_view
    #      (
    #          template_name='app/login.html',
    #          authentication_form=forms.BootstrapAuthenticationForm,
    #          extra_context=
    #          {
    #              'title': 'Log in',
    #              'year' : datetime.now().year,
    #          }
    #      ),
    #      name='login'),
    # path('logout/', LogoutView.as_view(next_page='/'), name='logout'),
    path('admin/', admin.site.urls),
]

movement/urls.py
from django.urls import path
from . import views

app_name = 'movement'

urlpatterns = [
    # FBV
    path('post/ajax/movement_plan', views.post_Movement_Plan, name="post_movement_plan"),
    path('post/ajax/m_cp_detail', views.post_CP_Detail, name="post_cp_detail"),
    path('get/ajax/m_cp_detail', views.get_CP_Detail, name="get_cp_detail"),
    path('post/ajax/m_unit_detail', views.post_Unit_Detail, name="post_unit_detail"),
    path('get/ajax/m_unit_detail', views.get_Unit_Detail, name="get_unit_detail"),
    path('get/ajax/m_packet_detail', views.get_Packet_Detail, name="get_packet_detail"),
    path('get/ajax/validate_brigade_name', views.validate_Brigade_Name, name="validate_brigade_name"),
    path('get/ajax/validate_brigade_acronym_name', views.validate_Brigade_Acronym_Name, name="validate_brigade_acronym_name"),
    path('get/ajax/validate_unit_name', views.validate_Unit_Name, name="validate_unit_name"),
    path('get/ajax/validate_unit_acronym_name', views.validate_Unit_Acronym_Name, name="validate_unit_acronym_name"),
    path('get/ajax/validate_mov_cp_no', views.validate_Mov_CP_No, name="validate_mov_cp_no"),
    path('get/ajax/validate_mov_unit_name', views.validate_Mov_Unit_Name, name="validate_mov_unit_name"),
    path('get/ajax/validate_mov_subunit_name', views.validate_Mov_SubUnit_Name, name="validate_mov_subunit_name"),
    path('get/ajax/validate_mov_subunit_pkt_no', views.validate_Mov_SubUnit_Pkt_No, name="validate_mov_subunit_pkt_no"),
    path('get/ajax/get_sx_plan', views.get_SX_Plan, name="get_sx_plan"),
    path('get/ajax/get_btn_text', views.get_Btn_Text, name="get_btn_text"),
    path('get/ajax/validate_mov_veh_qty', views.validate_Mov_Veh_Qty, name="validate_mov_veh_qty"),
    # Base
    path('', views.Movement_PlanBaseView.as_view(), name="movement_plan_base"),
    # View
    path('list_movement_plan/', views.Movement_PlanListView.as_view(), name="list_movement_plan"),
    path("<brigade>/<int:pk>/", views.Movement_PlanDetailView.as_view(), name="detail_movement_plan"),
    path("<brigade>/<unit>/<int:pk>/", views.Unit_DetailView.as_view(), name="detail_movement_plan_by_unit"),
    # Create
    path("create_list_unit/", views.Create_UnitCreateListView.as_view(), name="create_list_unit"),
    path("create_list_brigade/", views.Create_BrigadeCreateListView.as_view(), name="create_list_brigade"),
    path("create_movement_plan/", views.Create_Movement_PlanView.as_view(), name="create_movement_plan"),
    path("create_list_mov_cp_detail/", views.Create_CP_DetailCreateListView.as_view(), name="create_list_mov_cp_detail"),
    path("create_list_mov_unit_detail/", views.Create_Unit_DetailCreateListView.as_view(), name="create_list_mov_unit_detail"),
    path("create_list_mov_packet_detail/", views.Create_Packet_DetailCreateListView.as_view(), name="create_list_mov_packet_detail"),
    # Edit
    path("list_edit_unit/", views.Edit_Unit_ListView.as_view(), name="list_edit_unit"),
    path("list_edit_brigade/", views.Edit_Brigade_ListView.as_view(), name="list_edit_brigade"),
    path("list_edit_movement_plan/", views.Edit_Movement_PlanListView.as_view(),
         name="list_edit_movement_plan"),
    path("list_edit_mov_cp_detail/", views.Edit_CP_DetailListView.as_view(), name="list_edit_mov_cp_detail"),
    path("list_edit_mov_unit_detail/", views.Edit_Unit_DetailListView.as_view(),
         name="list_edit_mov_unit_detail"),
    path("list_edit_mov_packet_detail/", views.Edit_Packet_DetailListView.as_view(),
         name="list_edit_mov_packet_detail"),
    # Update
    path("update_unit_<int:pk>/", views.Update_UnitView.as_view(), name="update_unit"),
    path("update_brigade_<int:pk>/", views.Update_BrigadeView.as_view(), name="update_brigade"),
    path("update_movement_plan_<int:pk>/", views.Update_Movement_PlanView.as_view(), name="update_movement_plan"),
    path("update_mov_cp_detail_<int:pk>/", views.Update_Mov_CP_DetailView.as_view(), name="update_mov_cp_detail"),
    path("update_mov_unit_detail_<int:pk>/", views.Update_Mov_Unit_DetailView.as_view(), name="update_mov_unit_detail"),
    path("update_mov_packet_detail_<int:pk>/", views.Update_Mov_Packet_DetailView.as_view(), name="update_mov_packet_detail"),
    # Delete
    path("delete_unit_<int:pk>/", views.Delete_UnitView.as_view(), name="delete_unit"),
    path("delete_brigade_<int:pk>/", views.Delete_BrigadeView.as_view(), name="delete_brigade"),
    path("delete_movement_plan_<int:pk>/", views.Delete_Movement_PlanView.as_view(), name="delete_movement_plan"),
    path("delete_mov_cp_detail_<int:pk>/", views.Delete_Mov_CP_DetailView.as_view(), name="delete_mov_cp_detail"),
    path("delete_mov_unit_detail_<int:pk>/", views.Delete_Mov_Unit_DetailView.as_view(), name="delete_mov_unit_detail"),
    path("delete_mov_packet_detail_<int:pk>/", views.Delete_Mov_Packet_DetailView.as_view(), name="delete_mov_packet_detail"),
]

startex/urls.py
from django.urls import path
from startex import views

app_name = 'startex'

urlpatterns = [
    # FBV
    path('post/ajax/startex_plan', views.post_StartEx_Plan, name="post_startex_plan"),
    path('post/ajax/sx_unit_detail', views.post_Unit_Detail, name="post_unit_detail"),
    path('get/ajax/sx_unit_detail', views.get_Unit_Detail, name="get_unit_detail"),
    path('get/ajax/sx_vehicle_detail', views.get_Vehicle_Detail, name="get_vehicle_detail"),
    path('get/ajax/validate_vehicle_name', views.validate_Vehicle_Name, name="validate_vehicle_name"),
    path('get/ajax/validate_sx_unit_name', views.validate_SX_Unit_Name, name="validate_sx_unit_name"),
    path('get/ajax/validate_sx_vehicle_name', views.validate_SX_Vehicle_Name, name="validate_sx_vehicle_name"),
    # Base
    path('', views.StartEx_PlanBaseView.as_view(), name="startex_plan_base"),
    # View
    path('list_startex_plan/', views.List_StartEx_PlanView.as_view(), name="list_startex_plan"),
    path("detail_startex_plan/<int:pk>/", views.Detail_StartEx_PlanView.as_view(), name="detail_startex_plan"),
    # Create
    path("create_list_sx_vehicle_data/", views.Create_List_SX_Vehicle_DataView.as_view(),
         name="create_list_sx_vehicle_data"),
    path("create_startex_plan/", views.Create_StartEx_PlanView.as_view(), name="create_startex_plan"),
    path("create_list_sx_unit_detail/", views.Create_List_SX_Unit_DetailView.as_view(),
         name="create_list_sx_unit_detail"),
    path("create_list_sx_vehicle_detail/", views.Create_List_SX_Vehicle_DetailView.as_view(),
         name="create_list_sx_vehicle_detail"),
    # Edit
    path("list_edit_vehicle_data/", views.list_edit_vehicle_dataView.as_view(), name="list_edit_vehicle_data"),
    path("list_edit_startex_plan/", views.List_Edit_StartEx_PlanView.as_view(), name="list_edit_startex_plan"),
    path("list_edit_sx_unit_detail/", views.List_Edit_SX_Unit_DetailView.as_view(), name="list_edit_sx_unit_detail"),
    path("list_edit_sx_vehicle_detail/", views.List_Edit_SX_Vehicle_DetailView.as_view(),
         name="list_edit_sx_vehicle_detail"),
    # Update
    path("update_sx_vehicle_data/<int:pk>/", views.Update_SX_Vehicle_DataView.as_view(), name="update_sx_vehicle_data"),
    path("update_startex_plan/<int:pk>/", views.Update_StartEx_PlanView.as_view(), name="update_startex_plan"),
    path("update_sx_unit_detail/<int:pk>/", views.Update_SX_Unit_DetailView.as_view(), name="update_sx_unit_detail"),
    path("update_sx_vehicle_detail/<int:pk>/", views.Update_SX_Vehicle_DetailView.as_view(),
         name="update_sx_vehicle_detail"),
    # Delete
    path("delete_sx_vehicle_data/<int:pk>/", views.Delete_SX_Vehicle_DataView.as_view(), name="delete_sx_vehicle_data"),
    path("delete_startex_plan/<int:pk>/", views.Delete_StartEx_PlanView.as_view(), name="delete_startex_plan"),
    path("delete_sx_unit_detail/<int:pk>/", views.Delete_SX_Unit_DetailView.as_view(), name="delete_sx_unit_detail"),
    path("delete_sx_vehicle_detail/<int:pk>/", views.Delete_SX_Vehicle_DetailView.as_view(), name="delete_sx_vehicle_detail"),
]

movement/models.py
from django.db import models
from django.conf import settings
from django.urls import reverse

# pip install misaka
# import misaka

ROUTE_CHOICES = [
    ('Motorway', 'Motorways'),
    ('Urban', 'Urban Roads'),
    ('None', 'Not Specified'),
]

from django.contrib.auth import get_user_model

User = get_user_model()


# Create your models here.
class Route_Type(models.Model):
    route_type = models.CharField(max_length=20, null=False, blank=False)
    acronym = models.CharField(max_length=20, null=True, blank=False)

    def __str__(self):
        return self.acronym


class Brigade(models.Model):
    brigade = models.CharField(max_length=50, null=False, blank=False)
    acronym = models.CharField(max_length=20, null=True, blank=False)

    def __str__(self):
        return self.acronym

    def get_update_url(self):
        return reverse(
            "movement:update_brigade",
            kwargs={
                "pk": self.pk,
            }
        )

    def get_delete_url(self):
        return reverse(
            "movement:delete_brigade",
            kwargs={
                "pk": self.pk,
            }
        )


class Movement_Data(models.Model):
    route_name = models.CharField(max_length=250, null=False, blank=False)
    exercise_name = models.CharField(max_length=100, null=False, blank=False)
    serial = models.CharField(max_length=100, null=True, blank=True)
    description = models.TextField(null=True, blank=True)
    start_time = models.TimeField(null=False, blank=False)
    start_date = models.DateField(null=False, blank=False)
    speed = models.PositiveIntegerField(null=True, blank=False)
    traffic_density = models.PositiveIntegerField(null=False, blank=False)
    packet_gap = models.PositiveIntegerField(null=True, blank=True)
    unit_gap = models.PositiveIntegerField(null=True, blank=True)
    # packet_size = models.PositiveIntegerField(null=True, blank=True)
    route_type = models.ForeignKey(Route_Type, related_name="movement_data", on_delete=models.PROTECT)
    # route_type = models.TextField(choices = ROUTE_CHOICES)
    created_at = models.DateTimeField(auto_now=True)
    created_by = models.ForeignKey(User, related_name="movement_data", on_delete=models.PROTECT)
    brigade = models.ForeignKey(Brigade, related_name="movement_data", on_delete=models.PROTECT)

    def __str__(self):
        return str(self.id) + " - " + self.route_name

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse(
            "movement:detail_movement_plan",
            kwargs={
                "brigade": self.brigade,
                "pk": self.pk,
            }
        )

    def get_update_url(self):
        return reverse(
            "movement:update_movement_plan",
            kwargs={
                "pk": self.pk,
            }
        )

    def get_delete_url(self):
        return reverse(
            "movement:delete_movement_plan",
            kwargs={
                "pk": self.pk,
            }
        )

    class Meta:
        ordering = ["-created_at"]
        # contraints = [
        #     models.UniqueConstraint(fields=['created_by', 'exercise_name', 'pk'], name ='created_exercise_pk')
        # ]


class Unit(models.Model):
    unit = models.CharField(max_length=50, null=False, blank=False)
    acronym = models.CharField(max_length=20, null=True, blank=False)

    def __str__(self):
        return self.acronym

    def get_update_url(self):
        return reverse(
            "movement:update_unit",
            kwargs={
                "pk": self.pk,
            }
        )

    def get_delete_url(self):
        return reverse(
            "movement:delete_unit",
            kwargs={
                "pk": self.pk,
            }
        )


class CP_Detail(models.Model):
    m_id = models.ForeignKey(Movement_Data, related_name="cp_detail", on_delete=models.CASCADE)
    cp_no = models.PositiveIntegerField(null=False, blank=False)
    distance = models.FloatField(null=False, blank=False)
    halt_time = models.PositiveIntegerField(null=False, blank=False)

    def __str__(self):
        return str(self.m_id) + " - CP" + str(self.cp_no)

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

    def get_update_url(self):
        return reverse(
            "movement:update_mov_cp_detail",
            kwargs={
                "pk": self.pk,
            }
        )

    def get_delete_url(self):
        return reverse(
            "movement:delete_mov_cp_detail",
            kwargs={
                "pk": self.pk,
            }
        )

    class Meta:
        ordering = ["id"]


class Unit_Detail(models.Model):
    m_id = models.ForeignKey(Movement_Data, related_name="unit_detail", on_delete=models.CASCADE)
    unit = models.ForeignKey(Unit, related_name="unit_detail", on_delete=models.PROTECT)
    packet_no = models.PositiveIntegerField(null=False, blank=False)
    vehicle_qty = models.PositiveIntegerField(null=False, blank=False)
    packet_allocated = models.BooleanField(null=False, blank=False, default=False)
    # packet_auto_populated = models.BooleanField(null=False, blank=False, default=False)

    def __str__(self):
        return str(self.m_id) + " - " + str(self.unit)

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse(
            "movement:detail_movement_plan_by_unit",
            kwargs={
                "unit": self.unit,
                "pk": self.pk,
                "brigade": self.m_id.brigade
            }
        )

    def get_update_url(self):
        return reverse(
            "movement:update_mov_unit_detail",
            kwargs={
                "pk": self.pk,
            }
        )

    def get_delete_url(self):
        return reverse(
            "movement:delete_mov_unit_detail",
            kwargs={
                "pk": self.pk,
            }
        )

    class Meta:
        ordering = ["id"]


class Packet_Detail(models.Model):
    u_id = models.ForeignKey(Unit_Detail, related_name="packet_detail", on_delete=models.CASCADE)
    subunit = models.CharField(max_length=50, null=False, blank=False)
    packet_no = models.PositiveIntegerField(null=False, blank=False)
    vehicle_qty = models.PositiveIntegerField(null=False, blank=False)

    def __str__(self):
        return str(self.u_id.m_id) + " - " + str(self.u_id.unit) + " - " + self.subunit

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

    def get_update_url(self):
        return reverse(
            "movement:update_mov_packet_detail",
            kwargs={
                "pk": self.pk,
            }
        )

    def get_delete_url(self):
        return reverse(
            "movement:delete_mov_packet_detail",
            kwargs={
                "pk": self.pk,
            }
        )

    class Meta:
        ordering = ["id"]

movement/templates/movement/create_mov_packet_detail.html
{% extends "movement/movement_layout_view.html" %}

{% block breadcrumb %}
    <li class="breadcrumb-item active"><a href="{% url 'movement:movement_plan_base' %}">Movement</a></li>
    <li class="breadcrumb-item active"><a href="{% url 'movement:create_movement_plan' %}">Create Movement Plan</a></li>
    <li class="breadcrumb-item active"><a href="{% url 'movement:create_list_mov_cp_detail' %}">CP Allocation</a></li>
    <li class="breadcrumb-item active"><a href="{% url 'movement:create_list_mov_unit_detail' %}">Unit Allocate</a></li>
    <li class="breadcrumb-item active">Subunit Allocation</li>
{% endblock %}

{% block searchbar %}
    <form class="d-flex" action="{% url 'movement:create_list_mov_packet_detail' %}">
      {% csrf_token %}
      <input class="form-control me-2" type="search" placeholder="Movement - Search" aria-label="Search" name="search">
      <button class="btn btn-success me-2" type="submit">Search</button>
    </form>
{% endblock %}

{% block content %}
    {% if request.user.is_authenticated %}
        <div id="liveAlertPlaceholder"></div>
        {% if searchbool %}
            <div class="container">
                <hr class="bg-danger border-2 border-top border-danger">
                <h2>Search Result</h2><br>
                {% if packet_details %}
                    {% for packet_detail in packet_details %}
                        <h3>{{forloop.counter}}. {{packet_detail.u_id}}</h3>
                        <p class="lead">ID: {{packet_detail.id}}</p>
                        <p>Sub-unit: {{packet_detail.subunit}}</p>
                        <p>Packet No: {{packet_detail.packet_no}}</p>
                        <p>Vehicle Qty: {{packet_detail.vehicle_qty}}</p>
                    {% endfor %}
                {% else %}
                    <p>Not found </p>
                {% endif %}
                <hr class="bg-danger border-2 border-top border-danger">
            </div>
        {% endif %}

    <div class="container">
      <div class="alert alert-info lead" role="alert">Subunit Allocation</div>
      {% load django_bootstrap5 %}
        <div class="container">
            <form method="POST" class="form">
                {% csrf_token %}
                {% bootstrap_form form layout='horizontal' %}
                {% bootstrap_button button_type="submit" class="btn btn-primary" content="Add" %}
                {% if sx_guide == 0 %}
                    <span class="spinner-grow spinner-grow-sm" role="status" aria-hidden="true"></span>
                {% endif %}
                <a id = 'id_done' class="ms-3 btn btn-primary" href="{% url done_url %}" role="button">{{ done_text }}</a>
          </form>
        </div>

        <div class="mt-5 alert alert-secondary lead" role="alert">
            List of allocated packets
        </div>

        <div class="row justify-content-left">
            <div class="col-auto">
                {% if packet_detail_create_list %}
                  <p hidden id="id_records">Could not retrive the packet records!</p>
                  <table id="id_p_list_view" class="table table-responsive table-striped table-bordered border-secondary mb-4">
                    <thead class="table-dark text-center">
                      <tr>
                        <th>ID</th>
                        <th>Sub-unit</th>
                        <th>Packet No</th>
                        <th>Vehicle Qty</th>
                        <th>Action</th>
                      </tr>
                    </thead>
                    <tbody>
                        {% if packet_detail_create_list %}
                            {% regroup packet_detail_create_list by u_id as packet_detail_create_list_by_u_id %}
                                {% for u_id in packet_detail_create_list_by_u_id %}
                                    <tr>
                                        <td>{{ u_id.grouper }}</td>

                                        <td>
                                            {% for name in u_id.list %}
                                                <div class="border-bottom" style="height:40px;">{{name.subunit}}</div>
                                            {% endfor %}
                                        </td>
                                        <td>
                                            {% for name in u_id.list %}
                                                <div class="border-bottom" style="height:40px;">{{name.packet_no}}</div>
                                            {% endfor %}
                                        </td>
                                        <td>
                                            {% for name in u_id.list %}
                                                <div class="border-bottom" style="height:40px;">{{name.vehicle_qty}}</div>
                                            {% endfor %}
                                        </td>

                                        <td>
                                        {% for packet_detail in packet_detail_create_list %}
                                            <div class="border-bottom" style="height:40px;">
                                                <a href="{{ packet_detail.get_delete_url }}" class="btn btn-danger btn-sm bi bi-x-square"></a>
                                                <a href="{{ packet_detail.get_update_url }}" class="btn btn-primary btn-sm bi bi-pen"></a>
                                            </div>
                                        {% endfor %}
                                        </td>
                                    </tr>
                                {% endfor %}
                        {% endif %}
                    </tbody>
                  </table>

                  {% include 'movement/pagination.html' %}

                {% else %}
                    <p>There are no records!</p>
                {% endif %}
            </div>
        </div>
        <script>
          const params = new URLSearchParams(window.location.search);
          var u_id = params.get("u_id");
          $('#id_u_id').val({{ u_id }});
          if (u_id != null){
            $('#id_u_id').val(u_id);
          }
          if (u_id != null & u_id != {{ u_id }}){
            $('#id_p_list_view').hide();
            $('#id_pagination').hide();
            $('#id_records').removeAttr('hidden');
          }else{
            $('#id_p_list_view').show();
            $('#id_pagination').show();
            $('#id_records').addAttr('hidden');
          }
        </script>
            </div>
      {% else %}
		<h1> You are not logged in</h1>
	{% endif %}
{% endblock %}

{% block scripts %}
<script>

    $("#id_vehicle_qty").change(function () {
      var u_id = $('#id_u_id').val();
      var mov_veh_qty = $(this).val();
      $.ajax({
        type: 'GET',
        url: "{% url 'movement:validate_mov_veh_qty' %}",
        data: {
          'mov_veh_qty': mov_veh_qty,
          'u_id': u_id
        },
        dataType: 'json',
        success: function (data) {
          if (data.qty_invalid) {
            alert(data.error_message);
            var vehQty = $("#id_vehicle_qty");
            vehQty.val("")
            vehQty.focus()
          }
        }
      });
    });

    $("#id_u_id").change(function (e) {
        e.preventDefault();
        // get the nickname
        var u_id = $(this).val();
        // GET AJAX request
        $.ajax({
            type: 'GET',
            url: "{% url 'movement:get_packet_detail' %}",
            data: {"u_id": u_id},
            success: function (response) {
                location.reload();
            },
            error: function (response) {
                console.log(response)
            }
        })
    })

    $("#id_subunit").change(function () {
      var u_id = $('#id_u_id').val();
      var mov_subunit_name = $(this).val();
      $.ajax({
        type: 'GET',
        url: "{% url 'movement:validate_mov_subunit_name' %}",
        data: {
          'mov_subunit_name': mov_subunit_name,
          'u_id': u_id
        },
        dataType: 'json',
        success: function (data) {
          if (data.is_taken) {
            alert(data.error_message);
            var vehName = $("#id_subunit");
            vehName.val("")
            vehName.focus()
          }
        }
      });
    });

    $("#id_packet_no").change(function () {
      var u_id = $('#id_u_id').val();
      var mov_subunit_pkt_no = $(this).val();
      $.ajax({
        type: 'GET',
        url: "{% url 'movement:validate_mov_subunit_pkt_no' %}",
        data: {
          'mov_subunit_pkt_no': mov_subunit_pkt_no,
          'u_id': u_id
        },
        dataType: 'json',
        success: function (data) {
          if (data.is_taken) {
            alert(data.error_message);
            var vehName = $("#id_packet_no");
            vehName.val("")
            vehName.focus()
          }
        }
      });
    });

    // Alert - Start
    var alertPlaceholder = document.getElementById('liveAlertPlaceholder');
    function alert_guide(header, body, extra, instruction, furtherinfo) {
        let code = "";
        code += "<div class=\"alert alert-success\" role=\"alert\">\n";
        code += "<p class=\"text-center bg-secondary text-white\">(Guide Mode)</p>\n";
        code += "  <h4 class=\"alert-heading\">" + header + "</h4>\n";
        code += "  <p>" + body + "</p>\n";
        code += "  " + extra + "\n";
        code += "  " + instruction + "\n";
        code += "  <p></br>" + furtherinfo + "</p>\n";
        code += "  <hr>\n";
        code += "  <p class=\"mb-0 alert alert-warning\"><small><strong>Note:</strong> The administrator has activated \
                    the guide mode on this web application.\n";

        code += "</div>\n";

        var wrapper = document.createElement('div');
        wrapper.innerHTML = code;
        alertPlaceholder.append(wrapper);
    }

    $(document).ready(function () {
        var header = "Finally, allocate subunits!";
        var body = "Enter a subunit name, its packet number and vehicle quantity, and then click the \"<code>Add</code>\" \
                button to allocate the new subunit to the unit you've opened. Repeat the process to allocate more subunits \
                the unit you've opened.";
        var extra = "<h5>For example:</h5>";
        var instruction = "<b>Subunit: </b>11 Signal Regiment</br><b>Packet no: </b>1</br><b>Vehicle qty: </b>10";
        var furtherinfo = "After subunits have been added, you can make changes to them by clicking the \"<code>Delete</code>\" or \"<code>Update</code>\" \
                    buttons. In the meantime, click on the \"<code>Back</code>\" button to allocate subunits to other units. Alternatively, you can use the dropdown. Finally, please select \"<code>Movement Plan</code>\" from the \"<code>View</code>\" dropdown menu on the left vertical \
                    navbar to view your Movement plan.";
        alert_guide(header, body, extra, instruction, furtherinfo);
    });
    // Alert - End
</script>
{% endblock scripts %}

movement/templates/movement/delete_brigade.html
{% extends "movement/movement_layout.html" %}

{% block breadcrumb %}
  <li class="breadcrumb-item active"><a href="{% url 'movement:movement_plan_base' %}">Movement</a></li>
  <li class="breadcrumb-item active">Delete Brigade</li>
{% endblock %}

{% block content %}
{% if request.user.is_authenticated %}
	<div class="container">
	  <div class="alert alert-danger lead" role="alert">
		Confirm Delete Brigade!
	  </div>
	  {% load django_bootstrap5 %}
		<div class="container">
			<form method="POST" class="form">
				{% csrf_token %}
			  <p>Are you sure you want to delete brigade "{{ object.brigade }}"?</p>
				{% bootstrap_button button_type="submit" class="btn btn-primary" content="Confirm" %}
				<a class="ms-3 btn btn-primary" href="{% url cancel_url %}" role="button">Cancel</a>
		  </form>
		</div>
	  </div>
  {% else %}
	<h1> You are not logged in</h1>
  {% endif %}
{% endblock %}

movement/templates/movement/delete_unit.html
{% extends "movement/movement_layout.html" %}

{% block breadcrumb %}
  <li class="breadcrumb-item active"><a href="{% url 'movement:movement_plan_base' %}">Movement</a></li>
  <li class="breadcrumb-item active">Delete Unit</li>
{% endblock %}

{% block content %}
	{% if request.user.is_authenticated %}
		<div class="container">
		  <div class="alert alert-danger lead" role="alert">
			Confirm Delete Unit!
		  </div>
		  {% load django_bootstrap5 %}
			<div class="container">
				<form method="POST" class="form">
					{% csrf_token %}
				  <p>Are you sure you want to delete unit "{{ object.unit }}"?</p>
					{% bootstrap_button button_type="submit" class="btn btn-primary" content="Confirm" %}
					<a class="ms-3 btn btn-primary" href="{% url cancel_url %}" role="button">Cancel</a>
			  </form>
			</div>
		</div>
	{% else %}
		<h1> You are not logged in</h1>
	{% endif %}
{% endblock %}